---
- name: yum repository
  copy:
    src=MariaDB.repo
    dest=/etc/yum.repos.d/MariaDB.repo
    owner=root
    group=root

- name: install
  yum: name={{ item }} state=present
  with_items:
    - MariaDB-server
    - MariaDB-client
    - MySQL-python

- name: configure my.cnf
  template:
    src=my.cnf.j2
    dest=/etc/my.cnf
  notify:
      - restart mysql

- name: start mariadb
  service: name=mysql state=started

- name: change default user to {{ mariadb.username }} / {{ mariadb.password }}
  mysql_user: name={{ mariadb.username }} password={{ mariadb.password }} host=localhost login_unix_socket={{ mariadb.config.mysqld.socket }}

- name: copy .my.cnf file for user root
  template:
    src=user-my.cnf.j2
    dest=/root/.my.cnf
    owner=root
    group=root
    mode=0600

- name: copy .my.cnf for user vagrant
  template:
    src=user-my.cnf.j2
    dest=/home/vagrant/.my.cnf
    owner=vagrant
    group=vagrant
    mode=0600
