---
- name: install
  yum: name={{ item }} state=present
  with_items:
    - redis

- name: configure redis.conf
  template:
    src=redis.conf.j2
    dest=/etc/redis.conf
  notify:
      - restart redis
