---
- name: yum repository
  copy:
    src=no1youknowz-hhvm.repo
    dest=/etc/yum.repos.d/no1youknowz-hhvm.repo
    owner=root
    group=root

- name: install
  yum: name={{ item }} state=present
  with_items:
    - hhvm
  notify:
    - restart hhvm

- name: install pgsql
  yum: name={{ item }} state=present
  with_items:
    - hhvm-ext-pgsql
  notify:
    - restart hhvm
  when: role.postgresql

- name: fix hhvm permission
  file:
    path=/usr/bin/hhvm
    owner=vagrant
    group=vagrant

- name: fix php-fcgi.sock permission
  file:
    path=/var/run/php-fcgi.sock
    owner=vagrant
    group=vagrant

- name: add hhvm.service
  copy:
    src=hhvm.service
    dest=/usr/lib/systemd/system/hhvm.service
    owner=root
    group=root

- name: reload systemd daemon
  command: /bin/systemctl daemon-reload

- name: start hhvm on boot
  service: name=hhvm enabled=yes

- name: configure php.ini
  template:
    src=php.ini.j2
    dest=/etc/hhvm/php.ini
  notify:
    - restart hhvm

- name: configure server.ini
  template:
    src=server.ini.j2
    dest=/etc/hhvm/server.ini
  notify:
    - restart hhvm

- name: link hhvm to php
  file:
    src=/usr/bin/hhvm
    dest=/usr/bin/php
    state=link
