---
- name: yum repository
  copy:
    src=php.repo
    dest=/etc/yum.repos.d/php.repo
    owner=root
    group=root
    
- name: install core, common, cli, fpm
  yum: name={{ item }} state=present
  with_items:
    - php70
    - php70-php-common
    - php70-php-cli
    - php70-php-fpm
  notify:
    - restart php70-php-fpm

- name: install memcached
  yum: name={{ item }} state=present
  with_items:
    - php70-php-pecl-memcached
  notify:
    - restart php70-php-fpm
  when: role.memcached

- name: install mongodb
  yum: name={{ item }} state=present
  with_items:
    - php70-php-pecl-mongodb
  notify:
    - restart php70-php-fpm
  when: role.mongodb

- name: install mysqlnd
  yum: name={{ item }} state=present
  with_items:
    - php70-php-mysqlnd
  notify:
    - restart php70-php-fpm
  when: role.mariadb

- name: install pgsql
  yum: name={{ item }} state=present
  with_items:
    - php70-php-pgsql
  notify:
    - restart php70-php-fpm
  when: role.postgresql

#- name: install redis
#  yum: name={{ item }} state=present
#  with_items:
#    - php70-php-pecl-redis
#  notify:
#    - restart php70-php-fpm
#  when: role.redis

#- name: install mssql
#  yum: name={{ item }} state=present
#  with_items:
#    - php70-php-mssql
#  notify:
#    - restart php70-php-fpm
#  when: role.freetds

- name: install modules
  yum: name="php70-php-{{ php.modules|join(',php70-php-') }}" state=present
  notify:
    - restart php70-php-fpm

- name: configure fpm php.ini
  template:
    src=php.ini.j2
    dest=/etc/opt/remi/php70/php.ini
  notify:
    - restart php70-php-fpm

- name: fpm config
  template:
    src=php-fpm.conf.j2
    dest=/etc/opt/remi/php70/php-fpm.conf
  notify:
    - restart php70-php-fpm

- name: link php binary
  file:
    src=/opt/remi/php70/root/bin/php
    dest=/usr/bin/php
    owner=root
    group=root
    state=link

- name: link php-cgi binary
  file:
    src=/opt/remi/php70/root/bin/php-cgi
    dest=/usr/bin/php-cgi
    owner=root
    group=root
    state=link

- name: link php-fpm binary
  file:
    src=/opt/remi/php70/root/sbin/php-fpm
    dest=/usr/sbin/php-fpm
    owner=root
    group=root
    state=link
