---
- name: add rpm key
  rpm_key: state=present key=https://packages.elastic.co/GPG-KEY-elasticsearch

- name: yum repository
  copy:
    src=elasticsearch.repo
    dest=/etc/yum.repos.d/elasticsearch.repo
    owner=root
    group=root

- name: install
  yum: name={{ item }} state=present
  with_items:
    - elasticsearch

- name: reload systemd daemon
  command: /bin/systemctl daemon-reload

- name: enable systemd daemon
  command: /bin/systemctl enable elasticsearch.service

- name: configure elasticsearch.yml
  template:
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
  notify:
      - restart elasticsearch

- name: uninstall all modules (there is no update support)
  command: "{{ elasticsearch.config['path.home'] }}/bin/plugin --remove {{ item }}"
  with_items: "{{ elasticsearch.plugins }}"

- name: install all modules
  command: "{{ elasticsearch.config['path.home'] }}/bin/plugin --install {{ item }}"
  with_items: "{{ elasticsearch.plugins }}"
