---
- name: yum repository
  copy:
    src=nodejs-0.12.repo
    dest=/etc/yum.repos.d/nodejs-0.12.repo
    owner=root
    group=root

- name: install
  yum: name={{ item }} state=present
  with_items:
    - nodejs
    - nodejs-devel

- name: npm install
  npm: name={{ item }} global=yes state=present
  with_items: nodejs.npm
