---
- name: yum repository
  copy:
    src=mongodb-org-3.0.repo
    dest=/etc/yum.repos.d/mongodb-org-3.0.repo
    owner=root
    group=root

- name: install
  yum: name={{ item }} state=present
  with_items:
    - mongodb-org

- name: start mongodb
  service: name=mongod state=started

- name: copy user script
  template:
    src=createuser.js.j2
    dest=/tmp/createuser.js

- name: add admin user
  command: mongo --shell /tmp/createuser.js

- name: copy .mongorc.js file for user root
  template:
    src=user-mongorc.js.j2
    dest=/root/.mongorc.js
    owner=root
    group=root
    mode=0600

- name: copy .mongorc.js for user vagrant
  template:
    src=user-mongorc.js.j2
    dest=/home/vagrant/.mongorc.js
    owner=vagrant
    group=vagrant
    mode=0600

- name: configure mongod.conf
  template:
    src=mongod.conf.j2
    dest=/etc/mongod.conf
  notify:
      - restart mongodb
