---
- name: install repository package
  yum: name=http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm state=present

- name: install
  yum: name={{ item }} state=present
  with_items:
    - nginx

- name: copy privatekey
  copy:
    src=privatekey
    dest=/etc/nginx/privatekey

- name: copy certificate
  copy:
    src=certificate
    dest=/etc/nginx/certificate

- name: nginx.conf
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx
