---

### yum

- name: yum | upgrade
  yum: name=* state=latest

- name: yum | install packages
  yum: name={{ item }} state=present
  with_items: "{{ general.packages }}"

### locale

- name: locale | Generate {{ general.config.locale }}
  command: /usr/bin/localedef -i {{ general.config.language }} -c -f {{ general.config.encoding }} {{ general.config.locale }}

### timezone

- name: timezone | Set /etc/localtime to {{ general.config.timezone }}
  command: /bin/cp /usr/share/zoneinfo/{{ general.config.timezone }} /etc/localtime

### keymap

- name: timezone | Set keymap to {{ general.config.keyboard.layout }}-{{ general.config.keyboard.variant }}
  command: /usr/bin/localectl set-keymap {{ general.config.keyboard.layout }}-{{ general.config.keyboard.variant }}

### grub

- name: grub | fix boot timeout
  lineinfile:
    dest=/etc/default/grub
    line='GRUB_TIMEOUT=3'
    regexp='^GRUB_TIMEOUT\='
    state=present
  register: fixbootparameter

- name: grub | update
  command: '/usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg'
  when: fixbootparameter.changed

### disable-transparent-hugepages

- name: disable-transparent-hugepages | add init script disable-transparent-hugepages
  copy:
    src=disable-transparent-hugepages
    dest=/etc/init.d/disable-transparent-hugepages
    owner=root
    group=root
    mode=755

- name: disable-transparent-hugepages | register init script disable-transparent-hugepages
  command: /usr/sbin/chkconfig --add disable-transparent-hugepages

- name: disable-transparent-hugepages | add config directory /etc/tuned/no-thp
  file: path=/etc/tuned/no-thp state=directory

- name: disable-transparent-hugepages | add config /etc/tuned/no-thp/tuned.conf
  copy:
    src=tuned.conf
    dest=/etc/tuned/no-thp/tuned.conf
    owner=root
    group=root

- name: disable-transparent-hugepages | register config /etc/tuned/no-thp/tuned.conf
  command: /usr/sbin/tuned-adm profile no-thp
