---

### yum

- name: yum | upgrade
  yum: name=* state=latest

- name: yum | install packages
  yum: name={{ item }} state=present
  with_items: general.packages

### locale

- name: locale | Generate {{ general.config.locale }}
  command: /usr/bin/localedef -i {{ general.config.language }} -c -f {{ general.config.encoding }} {{ general.config.locale }}

### timezone

- name: timezone | Set /etc/localtime to {{ general.config.timezone }}
  command: /bin/cp /usr/share/zoneinfo/{{ general.config.timezone }} /etc/localtime

### keymap

- name: timezone | Set keymap to {{ general.config.keymap }}
  command: /usr/bin/localectl set-keymap {{ general.config.keymap }}

### bash

- name: bash | copy .bash_vagrant for user vagrant
  template:
    src=bash_vagrant.j2
    dest=/home/vagrant/.bash_vagrant
    owner=vagrant
    group=vagrant

- name: bash | register .bash_vagrant for user vagrant
  lineinfile: dest=/home/vagrant/.bashrc line='. ~/.bash_vagrant'

- name: bash | copy .bash_vagrant for user root
  template:
    src=bash_vagrant.j2
    dest=/root/.bash_vagrant
    owner=root
    group=root

- name: bash | register .bash_vagrant for user root
  lineinfile: dest=/root/.bashrc line='. ~/.bash_vagrant'

### grub

- name: grub | fix boot timeout
  lineinfile:
    dest=/etc/default/grub
    line='GRUB_TIMEOUT=3'
    regexp='^GRUB_TIMEOUT\='
    state=present
  register: fixbootparameter

- name: grub | update
  command: '/usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg'
  when: fixbootparameter.changed

### disable-transparent-hugepages

- name: disable-transparent-hugepages | add init script disable-transparent-hugepages
  copy:
    src=disable-transparent-hugepages
    dest=/etc/init.d/disable-transparent-hugepages
    owner=root
    group=root
    mode=755

- name: disable-transparent-hugepages | register init script disable-transparent-hugepages
  command: /usr/sbin/chkconfig --add disable-transparent-hugepages

- name: disable-transparent-hugepages | add config directory /etc/tuned/no-thp
  file: path=/etc/tuned/no-thp state=directory

- name: disable-transparent-hugepages | add config /etc/tuned/no-thp/tuned.conf
  copy:
    src=tuned.conf
    dest=/etc/tuned/no-thp/tuned.conf
    owner=root
    group=root

- name: disable-transparent-hugepages | register config /etc/tuned/no-thp/tuned.conf
  command: /usr/sbin/tuned-adm profile no-thp
