---
- name: yum | upgrade
  yum: name=* state=latest

- name: yum | install packages
  yum: name={{ item }} state=latest
  with_items: general.packages

- name: locale | Generate {{ general.config.locale }}
  command: /usr/bin/localedef -i {{ general.config.language }} -c -f {{ general.config.encoding }} {{ general.config.locale }}

- name: timezone | Set /etc/localtime to {{ general.config.timezone }}
  command: /bin/cp /usr/share/zoneinfo/{{ general.config.timezone }} /etc/localtime

- name: bash | copy .bash_vagrant for user vagrant
  template:
    src=bash_vagrant.j2
    dest=/home/vagrant/.bash_vagrant
    owner=vagrant
    group=vagrant

- name: bash | register .bash_vagrant for user vagrant
  lineinfile: dest=/home/vagrant/.bashrc line='. ~/.bash_vagrant'

- name: bash | copy .bash_vagrant for user root
  template:
    src=bash_vagrant.j2
    dest=/root/.bash_vagrant
    owner=root
    group=root

- name: bash | register .bash_vagrant for user root
  lineinfile: dest=/root/.bashrc line='. ~/.bash_vagrant'

- name: grub | fix boot timeout
  lineinfile:
    dest=/etc/default/grub
    line='GRUB_TIMEOUT=3'
    regexp='^GRUB_TIMEOUT\='
    state=present
  register: fixbootparameter

- name: grub | fix boot parameter
  lineinfile:
    dest=/etc/default/grub
    line='GRUB_CMDLINE_LINUX="rd.lvm.lv=centos/root rd.lvm.lv=centos/swap crashkernel=auto rhgb quiet transparent_hugepage=never"'
    regexp='^GRUB_CMDLINE_LINUX\='
    state=present
  register: fixbootparameter

- name: grub | update
  command: /usr/sbin/grub2-mkconfig -o "$(/bin/readlink /etc/grub2.conf)"
  when: fixbootparameter.changed
