---
- name: install repository package
  yum: name=http://yum.postgresql.org/9.4/redhat/rhel-7-x86_64/pgdg-centos94-9.4-2.noarch.rpm state=present

- name: install
  yum: name={{ item }} state=present
  with_items:
    - postgresql94
    - postgresql94-server
    - python-psycopg2

- name: check if the data are allready initialized
  stat: path={{ postgresql.config.data_directory }}/postgresql.conf
  register: data_allready_initialized

- name: initialize data
  command: /usr/pgsql-9.4/bin/postgresql94-setup initdb
  when: data_allready_initialized.stat.exists == false

- name: start postgresql
  service: name=postgresql-9.4 state=started

- name: change default user to {{ postgresql.username }} / {{ postgresql.password }}
  sudo_user: postgres
  postgresql_user: name={{ postgresql.username }} password={{ postgresql.password }} role_attr_flags=SUPERUSER

- name: copy .pgpass
  template:
    src=user-pgpass.j2
    dest=/var/lib/pgsql/.pgpass
    owner=postgres
    group=postgres
    mode=0600

- name: configure postgresql.conf
  template:
    src=postgresql.conf.j2
    dest={{ postgresql.config.data_directory }}/postgresql.conf
  notify:
      - restart postgresql
